### ISSUE TITLE
IdentityAgent: proof from RootUpdater when getting claim proofs

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#169]
in `GetAllClaims`, `GetAllEmittedClaims`.
This needs first to have implemented #167

**Comment by ed255** [comment]
Here the 'Obtain a proof of the root.' function of the RootUpdater will be used.  Note that this function may not return after some time (maybe some minutes).

I think GetAllClaims and GetAllEmittedClaims should not request a proof for each claim.  There's already functions to requests proofs `GetClaimByHi`, that will probably need to be modified to be asyncronous in some way.

**Comment by arnaucube** [comment]
Deprecated
