### ISSUE TITLE
MerkleTree: make more usable and intuitive

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#170]
change merkletree calls and structs, to make it more usable
- to `addClaim` pass a `Claim` interface object instead of `Entry`
- avoid needing to go through `[]byte -> Elements -> Data -> Entry -> Entrier/Claim...`
- more usable parsers from `Claim` to `[]byte`,  `Leaf` to `Claim` and vice versa

**Comment by ed255** [comment]
1. Remember that go doesn't have generics, so there will be some patterns that would be nice to have but can't be done.  Nevertheless we could explore go code generations to have some degree of generics
2. The `Entrier` interface name was chosen following the go convention: https://golang.org/doc/effective_go.html#interface-names  If a different interface name is used, it should still follow the go convention.
