### ISSUE TITLE
Define a standard auth method for root update (state transition)

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#185]
Previously we used an Ethereum mesage signature with an ethereum EC key.  Ethereum message signatures have a string prefixed (as I understand, to avoid tricking a signer into signing a transaction, which doesn't use the prefix).  We also concatenated the signature date so that we could check for recently signed messages.

Now we are using babyjub signature.  Some endpoints of the relay require authentication showing proof of controling the kOp of the identity.  We should define a relay request signature scheme.

**Comment by arnaucube** [comment]
we can define that to transition from one state to another of an identity, need to provide the old state (old root) and the new state (new root). In this way we avoid reply attacks (an attacker sending an old signed root after some time)

**Comment by ed255** [comment]
For now we will sign the following elements: [SigPrefixSetState, oldState, newState]

All signatures should add a prefix to specify a prefix to indicate what they are signing (what the action of the signature means)

**Comment by arnaucube** [comment]
Related: https://github.com/iden3/contracts/issues/26
