### ISSUE TITLE
Update definition of ClaimAuthorizeService

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#187]
Currently ClaimAuthorizeService has the following fields:
- ServiceType: serviceType `// type ServiceType [ServiceTypeLen]byte`
- ServiceAddr: HashString(serviceAddr),
- ServicePubK: HashString(servicePubK),
- ServiceUrl:  HashString(serviceUrl),

For the relay authorization use case, I believe we only need an ID as a field.

A Relay also has an URL but I'm not sure what we get by adding that to a claim, because the relay could easily change the URL in the future and only the client should care about it.

A Relay also has a kOp, but I'm not sure this should be in the claim, as there should be a publicly verifiable way to link a kOp with the relay ID.

Since we need an ID in this claim, we should discuss if all the services referred by this claim have an identity or not, and if it's the later case, maybe we should split this claim into two different claims?

Edit: I also believe there's no need to hash the ID.

**Comment by ed255** [comment]
Proposal:
```go
// ClaimAuthorizeService is a claim to authorize a Service for the identity that performs the claim
type ClaimAuthorizeService struct {
	// Version is the claim version.
	Version uint32
	// ServiceType is the type of the authorized service
	ServiceType *ServiceType
	// ID is the ID of the Service
	ID *core.ID
}
```

**Comment by arnaucube** [comment]
- agree on referring services by ID
- agree on `ClaimAuthorizeService` proposal

The internal structure of the byte array for the claim:

```
e_3: [ 64  bits] claim type
     [ 32  bits] version
     [ 64  bits] service type
     [ 93 bits] 0
e_2: [ 248 bits] ID
     [ 5   bits] 0
e_1: [ 253 bits] 0
e_0: [ 253 bits] 0
```
```
0 <---> N bytes
[ 0 ] [ 0 ] [ 0 | ID ] [0 | service type | ver | type]
 e0    e1     e2               e3
```
Being all the data in the `Index` part.
