### ISSUE TITLE
Relay UpdateRoot check published root to be last version

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#192]
Relay only accepts updates of roots if:
- update msg contains:
    - `old root`
    - `new root`

and `old root` is in the tree as last version of that claim.
To ensure that the identity state transition is from the current root to a new one.

Edit by @ed255: If there's no setRoot for the id, an empty old root is accepted and required.
TODO: Define empty.

**Comment by ed255** [comment]
Deprecated.  All the logic is now handled in the Issuer with PublishState and SyncIdenStatePublic
