### ISSUE TITLE
Specify bidirectional communication between new App Instance and Wallet

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#221]
Establish bidirectional communication between new `App Instance` and `Wallet`, when the `App Instance` does not have configured `Identity Agent` yet.

Assumptions:
- Wallet is in a smartphone/tablet with camera
- Wallet native (smartphone/tablet)
- App Instance can be:
  - App in native or webapp in browser
  - App with camera or without
  - App in same device as wallet or different device

**Comment by arnaubennassar** [comment]
Work in progress [here](https://hackmd.io/eLsYiND-Tbi1mSExwAH2gA?edit)

**Comment by arnaucube** [comment]
Deprecated
