### ISSUE TITLE
Proposal: t *testing.T as first parameter

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#262]
In order to follow the testify style 
```go
assert.Equal(t, "value", variable)
```
the proposal is for the `testgen` module, when `*testing.T` is required (for example in https://github.com/iden3/go-iden3-core/blob/master/testgen/testgen.go#L46 ):

```go
// instead of:
func CheckTestValue(key string, value interface{}, t *testing.T) {
// which in use is:
testgen.CheckTestValue("0_HIndex", e.HIndex().Hex(), t)

// would look like:
func CheckTestValue(t *testing.T, key string, value interface{}) {
// which in use would be:
testgen.CheckTestValue(t, "0_HIndex", e.HIndex().Hex())
```

In this way across all the code we follow the same order when writing tests

**Comment by ed255** [comment]
I like this proposal!

**Comment by arnaucube** [comment]
Also:
in the `testgen.go`:
When calling the `assert` use `expected value, actual value` order :
```go
assert.Equal(t, "expected value", variable)
```
