### ISSUE TITLE
IdenPub implement modules

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#275]
The Identity State is formed with three Merkle Trees, where two of them need to be publicly accessible by the Holder.  These two Trees are: Revocation Tree, Roots Tree.

Read access to the Public data of the identity will be handled via the interface `IdenPubReader` defined in `components/idenpubreader/idenpubreader`.  It could also be a `service` instead of component if it fits better.

Write access to the Public data of the identity will be handled via the interface `IdenPubWriter` defined in `components/idenpubwriter/idenpubwriter`.  It could also be a `service` instead of component if it fits better.

Both interfaces require a mock implementation.

The place where this public data is offered is specified via an url.  For now we have thought about two protocols:
- `ipfs://...`
- `https://...`

The first version will only implement the https version for both reading and writing.

The leaves of the Roots Tree are:
- hi: `Root`
- hv: `0`

The leaves of the Revocation Tree are:
- hi: bigInt(`Nonce`)
- hv: bigInt(`Version`)

**Comment by arnaucube** [comment]
Note on the leafs of the RootsTree & Revocation Tree:
- The current implementation of the merkletree is designed for Entries that have the Data parameter
- Some of the options:
    - refactor/rebuild the merkletree implementation to allow edge cases such as setting the Hi & Hv instead of the Data (and not using the Data when calculating the siblings branches)
    - use a new noteType for those edge cases or use a 'magic number' for the Data on those cases
    - implement a separated merkletree designed for this new behaviour
    - not using Hi & Hv directly for the Roots Tree & Revocation Tree, and use a new Claim type for those cases

We talked (offline) about this, and decided to go with the 4th option (*not using Hi & Hv directly for the Roots Tree & Revocation Tree, and use a new Claim type for those cases*)

**Comment by arnaucube** [comment]
Leafs for the leafs of RootsTree & RevocationTree (`LeafRoT` and `LeafReT`) in this issue: #278
