### ISSUE TITLE
Implement a demo verifier server

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#306]
Here: https://github.com/iden3/go-iden3-servers-demo

The server should have the following endpoints:
# Public
- VerifyClaim

**Comment by arnaucube** [comment]
Follows the same error style than issuer (https://github.com/iden3/go-iden3-core/issues/305#issuecomment-588922687):
```go
type ServerError struct {
        Err string `json:"error"`
}
```

Endpoints spec:
- url prefix: `/api/unstable`

# Public
## Request claim verification
- method: POST
- url: `/verify`
- input: 
```
{
  credential: proof.CredentialValidity // max len: 80 bytes
}
```
- output:
```
200 OK
```
