### ISSUE TITLE
Verify BabyJubJub signature in the smart contract initState & setState calls

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#311]
Depends #294

**Comment by arnaucube** [comment]
Depends #322

**Comment by arnaucube** [comment]
Progress in https://github.com/iden3/contracts/commit/880ec6648de4a9551ffe5664645b0221c103e557
Current state:
- babyjubjub signature verification integrated with the state publishing smart contract
- initState test added
  - currently working partially with data generated by `go-iden3-core`
- Also updating `go-iden3-core` in the branch https://github.com/iden3/go-iden3-core/tree/feature/issuer-contract-integration to integrate with the smart contract

**Comment by arnaucube** [comment]
Progress in the PR https://github.com/iden3/contracts/pull/27
